public enum SEType
{
        PlayerHit,
        PlayerWalk,
        PlayerRun,
        EnemyHit,
        EnemyWalk,
        EnemyDie,
        Explosion,
        SelfDestruction,
        Gun,
        Shotgun,
        PlayerGun,
        GunDrop,
        GunPikUp,
        OverHeat,
        Reload,
        CancelButton,
        NextButton,
        SettingButton,
        Homing,
        recovery
}